site_name: IEEE 802.11 Notes
nav:
  - Home: index.md
  - IEEE 802.11 In-depth:
    - "802.11协议精读1:学习资料整理": ieee80211_in_depth/ieee80211_protocol_study_1_related_materials.md
    - "802.11协议精读2:DCF与CSMA/CA": ieee80211_in_depth/ieee80211_protocol_study_2_dcf_and_csmdca.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

# 引入 Mermaid 的 JavaScript 库
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 可选：自定义 Mermaid 主题或配置
extra_css:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.css